Source: Updates
Source: Log.e to Log.d for Release-based Builds
MediaManager: AlbumDuping: Resolve NullPointerException

NullPointerException Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nixholas.materialtunes/com.nixholas.materialtunes.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
      at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
          at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
              at android.app.ActivityThread.main(ActivityThread.java:6682)
                at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                      at com.nixholas.materialtunes.Media.MediaManager.findDuplicateAlbum(SourceFile:622)
                        at com.nixholas.materialtunes.Fragments.Adapters.DataAdapter.b(SourceFile:147)
                          at com.nixholas.materialtunes.Fragments.Adapters.DataAdapter.run(SourceFile:214)
                            at com.nixholas.materialtunes.MainActivity.onCreate(SourceFile:244)
                              at android.app.Activity.performCreate(Activity.java:6942)
                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                    ... 9 more

Signed-off-by: nixxholas <nixholas@outlook.com>